source 'https://rubygems.org'

# TODO: PRs were accepted, which version now?
gem 'rb_tuntap', '~> 0.2.1', git: 'https://github.com/TJNII/rb_tuntap.git'

gem 'bindata', '~> 2.4'
gem 'ipaddr', '~> 1.2.5'

gem 'sysvmq', '~> 0.2'

gem 'persistent_http', '~> 2.0', git: 'https://github.com/ag-TJNII/persistent_http.git', branch: 'TJNII-ssl_verify'

# Prometheus/API dependencies
gem 'prometheus-client', '~> 4.0'

gem 'puma', '~> 6.0'
gem 'rackup', '~> 2.2'
gem 'sinatra', '~> 4.1'
gem 'sinatra-contrib', '~> 4.0'

gem 'jwt', '~> 2.8'

group 'development' do
  gem 'rspec', '~> 3.8'
  gem 'rubocop', '~> 1.22.0'
  gem 'simplecov', '~> 0.16'
end
