# NOTE: Networks:
#   This config assumes the host IP is 192.168.128.1 with the network being 192.168.128.0/24
#   192.168.129.0/24 is used for the mesh.
#   These values will likely need tuning depending on the host config.
---
tun_mesh:
  config_version: 1.1
  clustering:
    bootstrap_groups:
      default:
        bootstrap_node_urls:
          - https://192.168.128.1:4567
          - https://192.168.128.1:4568

    control_api_advertise_url: https://192.168.128.1:4569
    auth:
      secret: bih0ohBoh4quib4apiehang6ohcahh9yo7eiw9ha

  control_api:
    ssl:
      cert_file_path: test_ssl/cert.pem
      key_file_path: test_ssl/key.pem

  logging:
    level: debug

  monitoring:
    method: prometheus
    prometheus:
      base_labels:
        env_name: local_test

  networking:
    ipv4:
      network_cidr: 192.168.129.0/24
      node_address_cidr: 192.168.129.30/26

  process:
    uid: 100010
